### ISSUE TITLE
Release v0.0.24

### ISSUE THREAD

**Issue by heph** [signalfx/signalfx-collectd-plugin#38]
@mdubbyap, v0.0.24 is referenced in the [latest master commit](https://github.com/signalfx/signalfx-collectd-plugin/commit/4ad8c6b468cbcd594106de96de4dec3c36141ade), but it's not tagged or published as a release. Please tag and publish v0.0.24

**Comment by mdubbyap** [comment]
Thanks! Updated, sorry about that.
